SELECT DISTINCT ca.REPORTED_SCH_YEAR AS SchoolYear,
	ca.DISTRICT_NAME AS DistrictName,
	ca.DISTRICT_NUMBER AS LeaIdentifer,
	ca.SCHOOL_NAME AS SchoolName,
	ca.SCHOOL_NUMBER AS SchoolIdentifier,
	ca.GTID AS StateStudentID,
	ca.LAST_NAME AS LastName,
	ca.FIRST_NAME AS FirstName,
	ps.StudentFullName,
	ca.BIRTH_DATE AS Dob,
	ps.Gender,
	ps.Grade,
	ca.SCALE_SCORE AS ScaleScore,
	LEFT(ca.ACHIEVEMENT_LEVEL, CHARINDEX('-', ca.ACHIEVEMENT_LEVEL) - 1) AS AchivementLevel,
	SUBSTRING(ca.ACHIEVEMENT_LEVEL, CHARINDEX('-', ca.ACHIEVEMENT_LEVEL) + 1, LEN(ca.ACHIEVEMENT_LEVEL) - CHARINDEX('-', ca.ACHIEVEMENT_LEVEL)) AS Achivement_Score,
	CASE
        WHEN CAST(SUBSTRING(ca.ACHIEVEMENT_LEVEL, CHARINDEX('-', ca.ACHIEVEMENT_LEVEL) + 1, LEN(ca.ACHIEVEMENT_LEVEL) - CHARINDEX('-', ca.ACHIEVEMENT_LEVEL)) AS DECIMAL(3,1)) BETWEEN 1.0 AND 2.1 THEN '1.0 - 2.1'
        WHEN CAST(SUBSTRING(ca.ACHIEVEMENT_LEVEL, CHARINDEX('-', ca.ACHIEVEMENT_LEVEL) + 1, LEN(ca.ACHIEVEMENT_LEVEL) - CHARINDEX('-', ca.ACHIEVEMENT_LEVEL)) AS DECIMAL(3,1)) BETWEEN 2.2 AND 2.8 THEN '2.2 - 2.8'
        WHEN CAST(SUBSTRING(ca.ACHIEVEMENT_LEVEL, CHARINDEX('-', ca.ACHIEVEMENT_LEVEL) + 1, LEN(ca.ACHIEVEMENT_LEVEL) - CHARINDEX('-', ca.ACHIEVEMENT_LEVEL)) AS DECIMAL(3,1)) BETWEEN 2.9 AND 3.1 THEN '2.9 - 3.1'
        WHEN CAST(SUBSTRING(ca.ACHIEVEMENT_LEVEL, CHARINDEX('-', ca.ACHIEVEMENT_LEVEL) + 1, LEN(ca.ACHIEVEMENT_LEVEL) - CHARINDEX('-', ca.ACHIEVEMENT_LEVEL)) AS DECIMAL(3,1)) BETWEEN 3.2 AND 3.4 THEN '3.2 - 3.4'
        WHEN CAST(SUBSTRING(ca.ACHIEVEMENT_LEVEL, CHARINDEX('-', ca.ACHIEVEMENT_LEVEL) + 1, LEN(ca.ACHIEVEMENT_LEVEL) - CHARINDEX('-', ca.ACHIEVEMENT_LEVEL)) AS DECIMAL(3,1)) BETWEEN 3.5 AND 3.7 THEN '3.5 - 3.7'
        WHEN CAST(SUBSTRING(ca.ACHIEVEMENT_LEVEL, CHARINDEX('-', ca.ACHIEVEMENT_LEVEL) + 1, LEN(ca.ACHIEVEMENT_LEVEL) - CHARINDEX('-', ca.ACHIEVEMENT_LEVEL)) AS DECIMAL(3,1)) BETWEEN 3.8 AND 4.0 THEN '3.8 - 4.0'
        WHEN CAST(SUBSTRING(ca.ACHIEVEMENT_LEVEL, CHARINDEX('-', ca.ACHIEVEMENT_LEVEL) + 1, LEN(ca.ACHIEVEMENT_LEVEL) - CHARINDEX('-', ca.ACHIEVEMENT_LEVEL)) AS DECIMAL(3,1)) BETWEEN 4.1 AND 4.2 THEN '4.1 - 4.2'
        WHEN CAST(SUBSTRING(ca.ACHIEVEMENT_LEVEL, CHARINDEX('-', ca.ACHIEVEMENT_LEVEL) + 1, LEN(ca.ACHIEVEMENT_LEVEL) - CHARINDEX('-', ca.ACHIEVEMENT_LEVEL)) AS DECIMAL(3,1)) >= 4.3 THEN '4.3+'
        ELSE NULL
    END AS CompositeScore,
	ca.SGP_LEVEL AS StudentGrowthPercentileLevel,
	ps.DistrictStudentId,
	'Access' AS assessmentcode,
	'ELL' AS Subject,
	ca.TenantId,
	ps.GAA,
	ps.[504status],
	ps.SpecialEdStatus,
	ps.disability,
	ps.Giftedandtalented,
	ps.EIP,
	ps.REIP,
	ps.Homeless,
	ps.ELL,
	ps.FRL,
	ps.IEP AS IEP,
	ps.Race AS Race,
	ps.SchoolCategory AS SchoolCategory,
	ps.Magnet AS Magnet
FROM main.clayton_Access ca
JOIN clayton_studentprogram ps ON ca.GTID = ps.StateStudentId
	AND ca.schoolyear = ps.schoolyear
	AND ca.tenantid = ps.tenantid



--This is Pull Test
