select * from [216854_PSAT10_20250505_023910]
select * from [216854_PSAT89_20250505_015013]
select distinct LATEST_RECORD_LOCATOR from [PSAT_MAY_2025_Export]

select 389+395

SELECT STRING_AGG(QUOTENAME(COLUMN_NAME), ', ') AS ColumnList
FROM (
    SELECT COLUMN_NAME 
    FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_NAME = '216854_PSAT10_20250505_023910'
    
    UNION
    
    SELECT COLUMN_NAME 
    FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_NAME = '216854_PSAT89_20250505_015013'
) AS CombinedColumns;


--select * into [PSAT_MAY_2025_Export] from (
select [ADDRESS_CITY], [ADDRESS_COUNTRY], [ADDRESS_COUNTY], [ADDRESS_LINE1], [ADDRESS_LINE2], [ADDRESS_PROVINCE], [ADDRESS_STATE], [ADDRESS_ZIP], [AI_CODE], [AI_NAME], [AP_ARTHIS], [AP_BIO], [AP_CALC], [AP_CHEM], [AP_COMPGOVPOL], [AP_COMPSCI], [AP_COMPSCIPRIN], [AP_ENGLANG], [AP_ENGLIT], [AP_ENVSCI], [AP_EURHIST], [AP_HUMGEO], [AP_MACECON], [AP_MICECON], [AP_MUSIC], [AP_PHYSI], [AP_PHYSMAG], [AP_PHYSMECH], [AP_PSYCH], [AP_SEMINAR], [AP_STAT], [AP_USGOVPOL], [AP_USHIST], [AP_WRLDHIST], [BIRTH_DATE], [CB_ID], [COHORT_YEAR], [DISTRICT_NAME], [DISTRICT_STUDENT_ID], [EBRW_CCR_BENCHMARK], [FILLER_1], [FILLER_2], [FILLER_3], [FILLER_4], [FILLER_5], [FILLER_6], NULL AS [FILLER_7], [GENDER], [GPO], [GRAD_DATE], [HS_STUDENT], [LATEST_PSAT_DATE], [LATEST_PSAT_EBRW], [LATEST_PSAT_GRADE], [LATEST_PSAT_KS_MATH_ADVANCED], [LATEST_PSAT_KS_MATH_ALGEBRA], [LATEST_PSAT_KS_MATH_GEOMETRY], [LATEST_PSAT_KS_MATH_PROBLEMSOLVING], [LATEST_PSAT_KS_MATH_SECTION], [LATEST_PSAT_KS_READING_CRAFT], [LATEST_PSAT_KS_READING_EXPRESSION], [LATEST_PSAT_KS_READING_INFORMATION], [LATEST_PSAT_KS_READING_SECTION], [LATEST_PSAT_KS_READING_STANDARD], [LATEST_PSAT_MATH_SECTION], [LATEST_PSAT_TOTAL], [LATEST_RECORD_LOCATOR], [MATH_CCR_BENCHMARK], [NAME_FIRST], [NAME_LAST], [NAME_MI], [NATIONAL_MERIT], [PERCENTILE_COUNTRY_MATH], [PERCENTILE_COUNTRY_RW], [PERCENTILE_COUNTRY_TOTAL], [PERCENTILE_NATREP_PSAT_EBRW], [PERCENTILE_NATREP_PSAT_MATH_SECTION], [PERCENTILE_NATREP_PSAT_TOTAL], [PERCENTILE_NATUSER_PSAT_EBRW], [PERCENTILE_NATUSER_PSAT_MATH_SECTION], [PERCENTILE_NATUSER_PSAT_TOTAL], [PERCENTILE_STATE_MATH], [PERCENTILE_STATE_RW], [PERCENTILE_STATE_TOTAL], [REPORT_DATE], [SECONDARY_ID], [SELECTION_INDEX], [STATE_STUDENT_ID], [YRS_9TO12]
from [216854_PSAT10_20250505_023910]
union 
select [ADDRESS_CITY], [ADDRESS_COUNTRY], NULL AS [ADDRESS_COUNTY], [ADDRESS_LINE1], [ADDRESS_LINE2], [ADDRESS_PROVINCE], [ADDRESS_STATE], [ADDRESS_ZIP], [AI_CODE], [AI_NAME], [AP_ARTHIS], NULL AS [AP_BIO], NULL AS [AP_CALC], NULL AS [AP_CHEM], NULL AS [AP_COMPGOVPOL], NULL AS [AP_COMPSCI], [AP_COMPSCIPRIN], NULL AS [AP_ENGLANG], NULL AS [AP_ENGLIT], NULL AS [AP_ENVSCI], [AP_EURHIST], [AP_HUMGEO], NULL AS [AP_MACECON], NULL AS [AP_MICECON], NULL AS [AP_MUSIC], NULL AS [AP_PHYSI], NULL AS [AP_PHYSMAG], NULL AS [AP_PHYSMECH], NULL AS [AP_PSYCH], [AP_SEMINAR], NULL AS [AP_STAT], NULL AS [AP_USGOVPOL], NULL AS [AP_USHIST], [AP_WRLDHIST], [BIRTH_DATE], [CB_ID], [COHORT_YEAR], [DISTRICT_NAME], [DISTRICT_STUDENT_ID], [EBRW_CCR_BENCHMARK], [FILLER_1], [FILLER_2], [FILLER_3], [FILLER_4], [FILLER_5], [FILLER_6], [FILLER_7], [GENDER], [GPO], NULL AS [GRAD_DATE], NULL AS [HS_STUDENT], [LATEST_PSAT_DATE], [LATEST_PSAT_EBRW], [LATEST_PSAT_GRADE], [LATEST_PSAT_KS_MATH_ADVANCED], [LATEST_PSAT_KS_MATH_ALGEBRA], [LATEST_PSAT_KS_MATH_GEOMETRY], [LATEST_PSAT_KS_MATH_PROBLEMSOLVING], [LATEST_PSAT_KS_MATH_SECTION], [LATEST_PSAT_KS_READING_CRAFT], [LATEST_PSAT_KS_READING_EXPRESSION], [LATEST_PSAT_KS_READING_INFORMATION], [LATEST_PSAT_KS_READING_SECTION], [LATEST_PSAT_KS_READING_STANDARD], [LATEST_PSAT_MATH_SECTION], [LATEST_PSAT_TOTAL], [LATEST_RECORD_LOCATOR], [MATH_CCR_BENCHMARK], [NAME_FIRST], [NAME_LAST], [NAME_MI], NULL AS [NATIONAL_MERIT], [PERCENTILE_COUNTRY_MATH], [PERCENTILE_COUNTRY_RW], [PERCENTILE_COUNTRY_TOTAL], [PERCENTILE_NATREP_PSAT_EBRW], [PERCENTILE_NATREP_PSAT_MATH_SECTION], [PERCENTILE_NATREP_PSAT_TOTAL], [PERCENTILE_NATUSER_PSAT_EBRW], [PERCENTILE_NATUSER_PSAT_MATH_SECTION], [PERCENTILE_NATUSER_PSAT_TOTAL], [PERCENTILE_STATE_MATH], [PERCENTILE_STATE_RW], [PERCENTILE_STATE_TOTAL], [REPORT_DATE], [SECONDARY_ID], NULL AS [SELECTION_INDEX], [STATE_STUDENT_ID], NULL AS [YRS_9TO12]
from [216854_PSAT89_20250505_015013]
--)a