SELECT count(1) FROM Stage.Duxbury_Course_Audit WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.Duxbury_Course_CleanRecords WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.Duxbury_Course_Deletes WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.Duxbury_Course_FailedRecords WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.Duxbury_Course_NoAction WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.Duxbury_Course_Stage WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Main.Duxbury_Course WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.Duxbury_CourseSection_Audit WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.Duxbury_CourseSection_CleanRecords WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.Duxbury_CourseSection_Deletes WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.Duxbury_CourseSection_FailedRecords WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.Duxbury_CourseSection_NoAction WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.Duxbury_CourseSection_Stage WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Main.Duxbury_CourseSection WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.Duxbury_DailyAttendance_Audit WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.Duxbury_DailyAttendance_CleanRecords WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.Duxbury_DailyAttendance_Deletes WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.Duxbury_DailyAttendance_FailedRecords WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.Duxbury_DailyAttendance_NoAction WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.Duxbury_DailyAttendance_Stage WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Main.Duxbury_DailyAttendance WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.Duxbury_Enrollment_Audit WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.Duxbury_Enrollment_CleanRecords WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.Duxbury_Enrollment_Deletes WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.Duxbury_Enrollment_FailedRecords WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.Duxbury_Enrollment_NoAction WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.Duxbury_Enrollment_Stage WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Main.Duxbury_Enrollment WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.Duxbury_StaffSections_Audit WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.Duxbury_StaffSections_CleanRecords WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.Duxbury_StaffSections_Deletes WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.Duxbury_StaffSections_FailedRecords WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.Duxbury_StaffSections_NoAction WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.Duxbury_StaffSections_Stage WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Main.Duxbury_StaffSections WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.Duxbury_StudentSections_Audit WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.Duxbury_StudentSections_CleanRecords WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.Duxbury_StudentSections_Deletes WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.Duxbury_StudentSections_FailedRecords WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.Duxbury_StudentSections_NoAction WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.Duxbury_StudentSections_Stage WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Main.Duxbury_StudentSections WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12DisabilityStudent_Audit WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12DisabilityStudent_CleanRecords WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12DisabilityStudent_Deletes WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12DisabilityStudent_FailedRecords WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12DisabilityStudent_NoAction WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12DisabilityStudent_Stage WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Main.K12DisabilityStudent WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12SpecialEducationStudent_Audit WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12SpecialEducationStudent_CleanRecords WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12SpecialEducationStudent_Deletes WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12SpecialEducationStudent_FailedRecords WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12SpecialEducationStudent_NoAction WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12SpecialEducationStudent_Stage WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Main.K12SpecialEducationStudent WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StaffAssignment_Audit WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StaffAssignment_CleanRecords WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StaffAssignment_Deletes WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StaffAssignment_FailedRecords WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StaffAssignment_NoAction WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StaffAssignment_Stage WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Main.K12StaffAssignment WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StaffContactEmail_Audit WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StaffContactEmail_CleanRecords WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StaffContactEmail_Deletes WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StaffContactEmail_FailedRecords WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StaffContactEmail_NoAction WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StaffContactEmail_Stage WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Main.K12StaffContactEmail WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StaffEmployment_Audit WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StaffEmployment_CleanRecords WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StaffEmployment_Deletes WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StaffEmployment_FailedRecords WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StaffEmployment_NoAction WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StaffEmployment_Stage WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Main.K12StaffEmployment WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StaffSectionAssignment_Audit WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StaffSectionAssignment_CleanRecords WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StaffSectionAssignment_Deletes WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StaffSectionAssignment_FailedRecords WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StaffSectionAssignment_NoAction WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StaffSectionAssignment_Stage WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Main.K12StaffSectionAssignment WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StudentDailyAttendance_Audit WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StudentDailyAttendance_CleanRecords WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StudentDailyAttendance_Deletes WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StudentDailyAttendance_FailedRecords WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StudentDailyAttendance_NoAction WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StudentDailyAttendance_Stage WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Main.K12StudentDailyAttendance WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StudentEnrollment_Audit WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StudentEnrollment_CleanRecords WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StudentEnrollment_Deletes WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StudentEnrollment_FailedRecords WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StudentEnrollment_NoAction WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StudentEnrollment_Stage WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Main.K12StudentEnrollment WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StudentOtherRaces_Audit WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StudentOtherRaces_CleanRecords WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StudentOtherRaces_Deletes WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StudentOtherRaces_FailedRecords WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StudentOtherRaces_NoAction WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StudentOtherRaces_Stage WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Main.K12StudentOtherRaces WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StudentProgram_Audit WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StudentProgram_CleanRecords WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StudentProgram_Deletes WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StudentProgram_FailedRecords WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StudentProgram_NoAction WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StudentProgram_Stage WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Main.K12StudentProgram WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StudentSectionEnrollment_Audit WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StudentSectionEnrollment_CleanRecords WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StudentSectionEnrollment_Deletes WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StudentSectionEnrollment_FailedRecords WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StudentSectionEnrollment_NoAction WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Stage.K12StudentSectionEnrollment_Stage WHERE schoolyear = 2026 AND tenantid = 26
SELECT count(1) FROM Main.K12StudentSectionEnrollment WHERE schoolyear = 2026 AND tenantid = 26