--MAIN
select count(1) from [Main].[WHPS_Students] where schoolyear = 2026 and tenantid = 38
select count(1) from [Main].[K12StudentEnrollment] where schoolyear = 2026 and tenantid = 38
select count(1) from [Main].[K12SpecialEducationStudent] where schoolyear = 2026 and tenantid = 38
select count(1) from [Main].[K12StudentProgram] where schoolyear = 2026 and tenantid = 38
select count(1) from [Main].[WHPS_Courses] where schoolyear = 2026 and tenantid = 38
select count(1) from [Main].[K12Course] where schoolyear = 2026 and tenantid = 38
select count(1) from [Main].[WHPS_Sections] where schoolyear = 2026 and tenantid = 38
select count(1) from [Main].[CourseSection] where schoolyear = 2026 and tenantid = 38
select count(1) from [Main].[WHPS_Teachers] where schoolyear = 2026 and tenantid = 38
select count(1) from [Main].[K12StaffContactEmail] where schoolyear = 2026 and tenantid = 38
select count(1) from [Main].[K12StaffEmployment] where schoolyear = 2026 and tenantid = 38
select count(1) from [Main].[WHPS_CoTeacherCourses] where schoolyear = 2026 and tenantid = 38
select count(1) from [Main].[K12StaffSectionAssignment] where schoolyear = 2026 and tenantid = 38
select count(1) from [Main].[WHPS_Log] where schoolyear = 2026 and tenantid = 38
select count(1) from [Main].[WHPS_Attendance] where schoolyear = 2026 and tenantid = 38
select count(1) from [Main].[WHPS_PeriodAttendance] where schoolyear = 2026 and tenantid = 38
select count(1) from [Main].[K12DisciplineAction] where schoolyear = 2026 and tenantid = 38
select count(1) from [Main].[K12DisciplineOffenders] where schoolyear = 2026 and tenantid = 38
select count(1) from [Main].[K12SchoolIncident] where schoolyear = 2026 and tenantid = 38
select count(1) from [Main].[WHPS_StudentSections] where schoolyear = 2026 and tenantid = 38
select count(1) from [Main].[K12StudentSectionEnrollment] where schoolyear = 2026 and tenantid = 38
select count(1) from [Main].[K12StudentDailyAttendance] where schoolyear = 2026 and tenantid = 38
select count(1) from [Main].[K12StudentPeriodAttendance] where schoolyear = 2026 and tenantid = 38
select count(1) from [Main].[K12DisabilityStudent] where schoolyear = 2026 and tenantid = 38
select count(1) from [Main].[K12StudentAcademicRecord] where schoolyear = 2026 and tenantid = 38

--AUDIT
select count(1) from [stage].[WHPS_Students_audit] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[K12StudentEnrollment_audit] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[K12SpecialEducationStudent_audit] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[K12StudentProgram_audit] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[WHPS_Courses_audit] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[K12Course_audit] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[WHPS_Sections_audit] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[CourseSection_audit] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[WHPS_Teachers_audit] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[K12StaffContactEmail_audit] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[K12StaffEmployment_audit] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[WHPS_CoTeacherCourses_audit] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[K12StaffSectionAssignment_audit] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[WHPS_Log_audit] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[WHPS_Attendance_audit] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[WHPS_PeriodAttendance_audit] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[K12DisciplineAction_audit] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[K12DisciplineOffenders_audit] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[K12SchoolIncident_audit] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[WHPS_StudentSections_audit] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[K12StudentSectionEnrollment_audit] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[K12StudentDailyAttendance_audit] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[K12StudentPeriodAttendance_audit] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[K12DisabilityStudent_audit] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[K12StudentAcademicRecord_audit] where schoolyear = 2026 and tenantid = 38

--NOACTION
select count(1) from [stage].[WHPS_Students_noaction] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[K12StudentEnrollment_noaction] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[K12SpecialEducationStudent_noaction] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[K12StudentProgram_noaction] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[WHPS_Courses_noaction] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[K12Course_noaction] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[WHPS_Sections_noaction] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[CourseSection_noaction] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[WHPS_Teachers_noaction] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[K12StaffContactEmail_noaction] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[K12StaffEmployment_noaction] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[WHPS_CoTeacherCourses_noaction] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[K12StaffSectionAssignment_noaction] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[WHPS_Log_noaction] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[WHPS_Attendance_noaction] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[WHPS_PeriodAttendance_noaction] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[K12DisciplineAction_noaction] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[K12DisciplineOffenders_noaction] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[K12SchoolIncident_noaction] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[WHPS_StudentSections_noaction] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[K12StudentSectionEnrollment_noaction] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[K12StudentDailyAttendance_noaction] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[K12StudentPeriodAttendance_noaction] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[K12DisabilityStudent_noaction] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[K12StudentAcademicRecord_noaction] where schoolyear = 2026 and tenantid = 38

--DELETES
select count(1) from [stage].[WHPS_Students_deletes] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[K12StudentEnrollment_deletes] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[K12SpecialEducationStudent_deletes] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[K12StudentProgram_deletes] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[WHPS_Courses_deletes] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[K12Course_deletes] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[WHPS_Sections_deletes] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[CourseSection_deletes] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[WHPS_Teachers_deletes] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[K12StaffContactEmail_deletes] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[K12StaffEmployment_deletes] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[WHPS_CoTeacherCourses_deletes] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[K12StaffSectionAssignment_deletes] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[WHPS_Log_deletes] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[WHPS_Attendance_deletes] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[WHPS_PeriodAttendance_deletes] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[K12DisciplineAction_deletes] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[K12DisciplineOffenders_deletes] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[K12SchoolIncident_deletes] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[WHPS_StudentSections_deletes] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[K12StudentSectionEnrollment_deletes] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[K12StudentDailyAttendance_deletes] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[K12StudentPeriodAttendance_deletes] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[K12DisabilityStudent_deletes] where schoolyear = 2026 and tenantid = 38
select count(1) from [stage].[K12StudentAcademicRecord_deletes] where schoolyear = 2026 and tenantid = 38

--FailedRecords
select count(1) from [Stage].[WHPS_Students_FailedRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[K12StudentEnrollment_FailedRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[K12SpecialEducationStudent_FailedRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[K12StudentProgram_FailedRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[WHPS_Courses_FailedRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[K12Course_FailedRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[WHPS_Sections_FailedRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[CourseSection_FailedRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[WHPS_Teachers_FailedRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[K12StaffContactEmail_FailedRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[K12StaffEmployment_FailedRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[WHPS_CoTeacherCourses_FailedRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[K12StaffSectionAssignment_FailedRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[WHPS_Log_FailedRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[WHPS_Attendance_FailedRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[WHPS_PeriodAttendance_FailedRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[K12DisciplineAction_FailedRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[K12DisciplineOffenders_FailedRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[K12SchoolIncident_FailedRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[WHPS_StudentSections_FailedRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[K12StudentSectionEnrollment_FailedRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[K12StudentDailyAttendance_FailedRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[K12StudentPeriodAttendance_FailedRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[K12DisabilityStudent_FailedRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[K12StudentAcademicRecord_FailedRecords] where schoolyear = 2026 and tenantid = 38

--CleanRecords
select count(1) from [Stage].[WHPS_Students_CleanRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[K12StudentEnrollment_CleanRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[K12SpecialEducationStudent_CleanRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[K12StudentProgram_CleanRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[WHPS_Courses_CleanRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[K12Course_CleanRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[WHPS_Sections_CleanRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[CourseSection_CleanRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[WHPS_Teachers_CleanRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[K12StaffContactEmail_CleanRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[K12StaffEmployment_CleanRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[WHPS_CoTeacherCourses_CleanRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[K12StaffSectionAssignment_CleanRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[WHPS_Log_CleanRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[WHPS_Attendance_CleanRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[WHPS_PeriodAttendance_CleanRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[K12DisciplineAction_CleanRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[K12DisciplineOffenders_CleanRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[K12SchoolIncident_CleanRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[WHPS_StudentSections_CleanRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[K12StudentSectionEnrollment_CleanRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[K12StudentDailyAttendance_CleanRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[K12StudentPeriodAttendance_CleanRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[K12DisabilityStudent_CleanRecords] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[K12StudentAcademicRecord_CleanRecords] where schoolyear = 2026 and tenantid = 38

--STAGE
select count(1) from [Stage].[WHPS_Students_Stage] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[K12StudentEnrollment_Stage] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[K12SpecialEducationStudent_Stage] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[K12StudentProgram_Stage] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[WHPS_Courses_Stage] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[K12Course_Stage] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[WHPS_Sections_Stage] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[CourseSection_Stage] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[WHPS_Teachers_Stage] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[K12StaffContactEmail_Stage] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[K12StaffEmployment_Stage] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[WHPS_CoTeacherCourses_Stage] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[K12StaffSectionAssignment_Stage] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[WHPS_Log_Stage] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[WHPS_Attendance_Stage] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[WHPS_PeriodAttendance_Stage] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[K12DisciplineAction_Stage] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[K12DisciplineOffenders_Stage] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[K12SchoolIncident_Stage] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[WHPS_StudentSections_Stage] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[K12StudentSectionEnrollment_Stage] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[K12StudentDailyAttendance_Stage] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[K12StudentPeriodAttendance_Stage] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[K12DisabilityStudent_Stage] where schoolyear = 2026 and tenantid = 38
select count(1) from [Stage].[K12StudentAcademicRecord_Stage] where schoolyear = 2026 and tenantid = 38